---
  child:
    "1":
      question: :starting_children_0?
      description: "child 1"
    "2":
      question: :starting_children_1?
      description: "child 2"
    "3":
      question: :starting_children_2?
      description: "child 3"
    "4":
      question: :starting_children_3?
      description: "child 4"
    "5":
      question: :starting_children_4?
      description: "child 5"
    "6":
      question: :starting_children_5?
      description: "child 6"
    "7":
      question: :starting_children_6?
      description: "child 7"
    "8":
      question: :starting_children_7?
      description: "child 8"
    "9":
      question: :starting_children_8?
      description: "child 9"
    "10":
      question: :starting_children_9?
      description: "child 10"